In [4]:
import numpy as np

# Generate a random 5x4 array with integers between 1 and 50
np.random.seed(0)  # For reproducibility
arr = np.random.randint(1, 51, size=(5, 4))

print("Original array:")
print(arr)

Original array:
[[45 48  1  4]
 [ 4 40 10 20]
 [22 37 24  7]
 [25 25 13  2]
 [39 40 24 47]]


## 1. Extract anti-diagonal elements

In [7]:
anti_diagonal = np.array([arr[i, arr.shape[1]-1-i] for i in range(min(arr.shape[0], arr.shape[1]))])
print("\nAnti-diagonal elements:", anti_diagonal)


Anti-diagonal elements: [ 4 10 37 25]


## 2. Compute maximum value in each row

In [10]:
row_max = np.max(arr, axis=1)
print("\nMaximum value in each row:", row_max)


Maximum value in each row: [48 40 37 25 47]


## 3. Create new array with elements <= overall mean

In [13]:
mean_val = np.mean(arr)
filtered_arr = arr[arr <= mean_val]
print("\nOverall mean:", mean_val)
print("Elements <= mean:", filtered_arr)


Overall mean: 23.85
Elements <= mean: [ 1  4  4 10 20 22  7 13  2]


## 4. Boundary traversal function

In [16]:
def numpy_boundary_traversal(matrix):
    if matrix.size == 0:
        return []
    
    rows, cols = matrix.shape
    boundary = []
    
    # Top row (left to right)
    boundary.extend(matrix[0, :cols].tolist())
    
    # Right column (top to bottom, excluding first element)
    if rows > 1:
        boundary.extend(matrix[1:, cols-1].tolist())
    
    # Bottom row (right to left, if there are multiple rows)
    if rows > 1:
        boundary.extend(matrix[rows-1, :cols-1][::-1].tolist())
    
    # Left column (bottom to top, excluding first and last elements)
    if cols > 1 and rows > 2:
        boundary.extend(matrix[1:rows-1, 0][::-1].tolist())
    
    return boundary

print("\nBoundary traversal:", numpy_boundary_traversal(arr))


Boundary traversal: [45, 48, 1, 4, 20, 7, 2, 47, 24, 40, 39, 25, 22, 4]
